import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from ".";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LIZA MOTOR",
  description: "Generated by Naveenkumar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#f5f5f5]`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
